sudo: required

services:
- docker

script:
- docker build -t glongzh/golang:alpine-gcc -f golang-gcc/Dockerfile golang-gcc
- docker run -v $(pwd):/go/src/github.com/wise2c-devops/pagoda -w /go/src/github.com/wise2c-devops/pagoda glongzh/golang:alpine-gcc go build
- docker build -t glongzh/pagoda:$TRAVIS_BRANCH .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push glongzh/pagoda:$TRAVIS_BRANCH
  on:
    all_branches: true
    #condition: "$TRAVIS_BRANCH =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+)?(-\\S*)?$"
